version: '3'

networks:
  projectname:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: project_name_nginx
    ports:
      - "8072:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - projectname

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_name_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - projectname
  mysql:
      image: mysql:5.7.29
      command: mysqld --sql_mode=""
      container_name: project_name_mysql
      restart: always
      ports:
        - "3308:3306"
      environment:
        MYSQL_DATABASE: laravel_app
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret456
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      networks:
        - projectname
      volumes:
        - ./sql_scripts:/docker-entrypoint-initdb.d
        - ./mysql:/var/lib/mysql

  composer:
    image: composer:latest
    container_name: project_name_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - projectname

  npm:
    image: node:12
    container_name: project_name_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_name_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - projectname
